CREATE PROCEDURE FI_SP_IncBeneficiario  
 @CPF VARCHAR(14),  
 @NOME VARCHAR(50),  
 @IDCLIENTE INT  
AS  
BEGIN  
 INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)  
 VALUES (@CPF, @NOME, @IDCLIENTE);  
END